{% set version = "2.9" %}

package:
  name: pytest-runner
  version: {{ version }}

source:
  fn: pytest-runner-{{version}}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-runner/pytest-runner-{{version}}.tar.gz
  sha256: 50378de59b02f51f64796d3904dfe71b9dc6f06d88fc6bfbd5c8e8366ae1d131

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - setuptools
    - pytest

test:
  imports:
    - ptr

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT
  summary: 'Invoke py.test as distutils command with dependency resolution.'

extra:
  recipe-maintainers:
    - dopplershift
