{% set version = "5.3.0" %}

package:
  name: pytest-runner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-runner/pytest-runner-{{ version }}.tar.gz
  sha256: ca3f58ff4957e8be6c54c55d575b235725cbbcf4dc0d5091c29c6444cfc8a5fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - setuptools
    - pytest

test:
  imports:
    - ptr

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Invoke py.test as distutils command with dependency resolution.
  dev_url: https://github.com/pytest-dev/pytest-runner

extra:
  recipe-maintainers:
    - dopplershift
    - ocefpaf
