travis:
  secure:
    BINSTAR_TOKEN: lOdKxl3fOg5khLIcXUJ8Ok7UXrTmq7S9EtWK4P8Lmil3C/PAuhpxQ4SXyeuDPmqGPke2326MBUAIFaAQ1nh2eleL2BBiEBeXmQ60VHwq5k04z936OlDbxJEjJvOnoYMWNGXmh+/2+R6Ts8PNMmx+POLTj6AU/xPwhboQryk1zzvnMDOjhlws9I+L52ba1B7N/q6n0IfNgzXcztw8CClwtFoA1s/vD3hkwcmh/Q5PoTe5HFOmB/1aJ2LeWCBITGV6c2fDRH57I7zhSTX2qiCb0GkfUsQ1wdUjDnOLDfBBDrpwt7DSx2u3qCnF3Yv1zaya4FDUqYZmk06ooLC7W1RoWWGDsXgyKsXASO5SZQME1m0wX9n206H6w3xVfl+F75BxS5WxBft059reHK8IHppk5/VJZxI253yHyIJQotjenwZI19HlfFIwMRk1EiM4pk8oA5Ry264o1qz6RUEl0lRNQaG3tphqXasRiwNAy93PW8CsR15Bn9snbKl5mc+Bg1M11Cuta8P2o/D05mJA+yEcMArL8puRWd1efqVJA7+b1SG4smtk4m2MxIiV2uhAsQ4YXFpbFoJp61DaPDrc6u++gGfz5H61PIFgFULAJfJ2RyHhdcdRzTaF1lL5XNL4RHQDcexscLNFgTei0qYO86N1CRH202wcdd5JfW82DmD4/xc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
