travis:
  secure:
    BINSTAR_TOKEN: XcsSRfm/c2MkfsmhfOgR4zUZ0AqB1+SRyCDqI+YPhLavja15mbyq4h5ocqMt3qKLtp+A04KIh7wtyNKFRulkj32ITu5er6fpD+XgEEB1WVj3pDmhAslQu2VPOUWTxltkZTEyoSBVBARW1vWRCVmgjYhetlutqiI9NftSJsHmIvDRbunA9EbTVFt8k6STWLes5Y2aEOEtXjfogx4zw52hA/TyJHOFzJisIIpUUGI7lfd5WW6yBB12VuZsXXxyWGBxgZMt08b4AX1eGQ9dgyBpmCy/T9ZGX4cwFi4fFEvOgjQ0w+PIwkNXtrVS+KzC7rF3bz86P6OJGtAXEC3l8D0SRUN1KmsWsMjyfeoZEh408Wnq44iyPcgrHJijKggqx0Nwt0upMoLD1xTf471P7kqQnJCSnh8QET+GieGeQpiqSvOmshLA6PGSwNY0yf5n5RNGyOrI5Liq5UR+vjsGNyxAXUypD4qy0fN0rHcL9XMOjh2LZZjlFce8u3N9FPlQlPvfc/JCZLTXsVmeJNAP1dTS96yjPVBAOt9pwgn83IDpBnE0RAtJtcW/5A221oFn8jmTimkHWckvloQNc7tx4qOWT2Jmd9zMjcmitQ0vIaZlyWHtNBRjWR/IrVO+9bEw2dBg9YTq3hpKF39OtSYysor01yMus77Y+Rljw+4JqP1wiko=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
